# Generated by Django 2.2.4 on 2020-02-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0003_auto_20200127_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multa',
        ),
        migrations.DeleteModel(
            name='SBU',
        ),
    ]
