# Generated by Django 2.2.4 on 2020-02-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Usuarios', '0002_auto_20200127_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente_transito',
            name='fotoA',
            field=models.FileField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
